conf.py:
  copyright: 2005-2019
  project: Calendar Base
  version: latest (2-dev)
  release: latest (2-dev)
  latex_documents:
  - - Index
    - cal.tex
    - Calendar Base
    - Jan Helke
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  html_theme_options:
    github_repository: TYPO3-extensions/cal
    github_branch: master
